CLOUDIGRADE_HOST: ${clowder.endpoints[?(@.app == 'cloudigrade')].hostname:localhost}
CLOUDIGRADE_PORT: ${clowder.endpoints[?(@.app == 'cloudigrade')].port:8080}
CLOUDIGRADE_INTERNAL_HOST: ${CLOUDIGRADE_HOST}
CLOUDIGRADE_INTERNAL_PORT: ${CLOUDIGRADE_PORT}

rhsm-subscriptions:
  jmx:
    tallyBean:
      hourlyTallyDurationLimitDays: 90d
  inventory-service:
    datasource:
      url: jdbc:postgresql://${INVENTORY_DATABASE_HOST:localhost}/${INVENTORY_DATABASE_DATABASE:insights}
      username: ${INVENTORY_DATABASE_USERNAME:insights}
      password: ${INVENTORY_DATABASE_PASSWORD:insights}
      driver-class-name: org.postgresql.Driver
      platform: postgresql
      hikari:
        connection-timeout: ${INVENTORY_DATABASE_CONNECTION_TIMEOUT_MS:30000}
        maximum-pool-size: ${INVENTORY_DATABASE_MAX_POOL_SIZE:10}
  # Use Spring Resource notation for this (e.g. "classpath:" or "file:")
  product-profile-registry-resource-location: classpath:product_profile_registry.yaml
  account-list-resource-location: ${ACCOUNT_LIST_RESOURCE_LOCATION:}

  cloudigrade-enabled: ${CLOUDIGRADE_ENABLED:false}
  cloudigrade-max-attempts: ${CLOUDIGRADE_MAX_ATTEMPTS:2}
  cloudigrade:
    url: http://${CLOUDIGRADE_HOST}:${CLOUDIGRADE_PORT}/api/cloudigrade/v2
    maxConnections: ${CLOUDIGRADE_MAX_CONNECTIONS:100}
    presharedKey: ${CLOUDIGRADE_PSK:}
    internal:
      url: http://${CLOUDIGRADE_INTERNAL_HOST}:${CLOUDIGRADE_INTERNAL_PORT}/internal/api/cloudigrade/v1
      presharedKey: ${CLOUDIGRADE_PSK:}
